apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: appcat-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appcat-controller
subjects:
  - kind: ServiceAccount
    name: appcat-controller
    namespace: appcat-controllers
