apiVersion: v1
kind: Service
metadata:
  name: appcat-controller
  namespace: appcat
  labels:
    appcat-controller: appcat-controller
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    appcat-controller: appcat-controller
